# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package publish and Docker Package publish

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Logging in to Docker
      run: docker login ghcr.io -u Hermanbence -p ${{ github.token }}

    - name: Build the Docker image
      run: docker build --tag ghcr.io/hermanbence/cubix/cloudnative/demo:actions .

    - name: Publishing the Docker image
      run: docker push ghcr.io/hermanbence/cubix/cloudnative/demo:actions
